name: Run tests for extensions on image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.set-tests.outputs.test-files }}
    steps:
      - uses: actions/checkout@v3
      - id: set-tests
        run: echo "test-files=$(ls tests/test_*.sh | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  test:
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-file: ${{ fromJson(needs.list-tests.outputs.test-files) }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: postgis-cloudsql:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Make scripts executable
      run: |
        chmod +x ./test.sh
        chmod +x ${{ matrix.test-file }}

    - name: Run ${{ matrix.test-file }}
      run: ./test.sh ${{ matrix.test-file }}
